"""plazas table added

Revision ID: 0d481b224a34
Revises: 37c86884e933
Create Date: 2026-09-10 18:14:40.434663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d481b224a34'
down_revision = '37c86884e933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plazas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plaza_identifier', sa.String(length=36), nullable=False),
    sa.Column('spv_identifier', sa.String(length=36), nullable=False),
    sa.Column('plaza_name', sa.String(length=255), nullable=False),
    sa.Column('plaza_code', sa.String(length=100), nullable=True),
    sa.Column('chainage', sa.String(length=100), nullable=True),
    sa.Column('district_state', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('tolling_start_date', sa.Date(), nullable=True),
    sa.Column('total_lanes', sa.Integer(), nullable=True),
    sa.Column('lhs_rhs_split', sa.String(length=100), nullable=True),
    sa.Column('hybrid_etc_only', sa.String(length=100), nullable=True),
    sa.Column('shift_pattern', sa.String(length=255), nullable=True),
    sa.Column('toll_day_cutoff', sa.String(length=100), nullable=True),
    sa.Column('om_contractor', sa.String(length=255), nullable=True),
    sa.Column('source_daily_tms_report', sa.Text(), nullable=True),
    sa.Column('event_calendar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['spv_identifier'], ['spvs.spv_identifier'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plazas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plazas_plaza_identifier'), ['plaza_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_plazas_spv_identifier'), ['spv_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plazas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plazas_spv_identifier'))
        batch_op.drop_index(batch_op.f('ix_plazas_plaza_identifier'))

    op.drop_table('plazas')
    # ### end Alembic commands ###
