"""spv creation

Revision ID: 37c86884e933
Revises: 41aeb97a27c7
Create Date: 2026-09-09 18:23:02.012084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c86884e933'
down_revision = '41aeb97a27c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spv_identifier', sa.String(length=36), nullable=False),
    sa.Column('company_identifier', sa.String(length=36), nullable=False),
    sa.Column('spv_name', sa.String(length=255), nullable=False),
    sa.Column('project_stretch_name', sa.String(length=255), nullable=True),
    sa.Column('nh_no', sa.String(length=50), nullable=True),
    sa.Column('chainage_from', sa.String(length=50), nullable=True),
    sa.Column('chainage_to', sa.String(length=50), nullable=True),
    sa.Column('length_km', sa.Integer(), nullable=True),
    sa.Column('rate_notification_no_date', sa.String(length=255), nullable=True),
    sa.Column('annual_revision_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wpi_linkage', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('rate_card_upload', sa.String(length=500), nullable=True),
    sa.Column('exempt_categories_policy', sa.Text(), nullable=True),
    sa.Column('local_monthly_pass_rules', sa.Text(), nullable=True),
    sa.Column('lead_bank_lender', sa.String(length=255), nullable=True),
    sa.Column('facility_limit', sa.String(length=255), nullable=True),
    sa.Column('escrow_bank', sa.String(length=255), nullable=True),
    sa.Column('revenue_share_premium_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('premium_escalation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_identifier'], ['companies.company_identifier'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spvs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spvs_company_identifier'), ['company_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_spvs_spv_identifier'), ['spv_identifier'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spvs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spvs_spv_identifier'))
        batch_op.drop_index(batch_op.f('ix_spvs_company_identifier'))

    op.drop_table('spvs')
    # ### end Alembic commands ###
