"""companies table created

Revision ID: c0e605db9867
Revises: 0002_create_analytics_tables
Create Date: 2026-09-09 14:46:35.106101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e605db9867'
down_revision = '0002_create_analytics_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_identifier', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('pan', sa.String(length=20), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pin', sa.String(length=20), nullable=True),
    sa.Column('holding_parent', sa.String(length=255), nullable=True),
    sa.Column('auditor', sa.String(length=255), nullable=True),
    sa.Column('financial_year_end', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_company_identifier'), ['company_identifier'], unique=True)
        batch_op.create_index(batch_op.f('ix_companies_short_code'), ['short_code'], unique=True)

    op.create_table('company_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_identifier', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_identifier'], ['companies.company_identifier'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_contacts_company_identifier'), ['company_identifier'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_contacts_company_identifier'))

    op.drop_table('company_contacts')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_short_code'))
        batch_op.drop_index(batch_op.f('ix_companies_company_identifier'))

    op.drop_table('companies')
    # ### end Alembic commands ###
